apiVersion: v1
kind: Service
metadata:
  name: insurance-deployment
spec:
  type: LoadBalancer
  selector:
    app: front-end       # must match pod label
  ports:
    - port: 8085         # external port
      targetPort: 8082   # container port
      protocol: TCP